name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^1.7.3
  firebase_auth: ^3.11.2  # Chỉ định phiên bản Firebase Auth tương ứng
  cloud_firestore: ^3.5.1
  embrace: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true